# Jekyll configuration for Open SDG platform
#
# You will need to change all of the capitalized variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "my-github-org" with "my-awesome-github-org"
# -- replace "open-sdg-site-starter" with "my-awesome-site-repo"
# -- replace "open-sdg-data-starter" with "my-awesome-data-repo"

# Replace this title as needed.
title: Indicators For The Sustainable Development Goals
# Replace the baseurl with the name of this repository.
baseurl: "/open-sdg-site-starter"
url: ""
data_dir: data
environment: staging

# Replace my-github-org and open-sdg-data-starter as needed.
remote_data_prefix: "https://SDG-kyrgyzstan.github.io/open-sdg-data-starter"

create_indicators:
  layout: indicator
create_goals:
  layout: goal-by-target
create_pages: true

analytics:
  ga_prod: ''
  
series_toggle: true

data_fields:
  units: UNIT_MEASURE
  series: SERIES
 
# Social media accounts.
#twitter: 'MyTwitterAccount'

# Replace the email addresses below.
email_contacts:
  questions: sdg_nsc@stat.kg
  suggestions: sdg_nsc@stat.kg
  functional: sdg_nsc@stat.kg

# Github Repo for Data
# Replace this value as needed.
repo_name: open-sdg-data-starter
branch: develop
# Replace this value as needed.
org_name: sustainabledevelopment-kyrgyzstan

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Кыргызская Республика
  adjective: Кыргызской Республики
  
  


# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true
  publications:
    output: true
    permalink: /publications/title.html
# Menu
menu:
  # Use these to customise the main navigation.
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /news
    translation_key: menu.news
  - path: /publications
    translation_key: menu.publications
  - path: /about
    translation_key: menu.about
  - path: /faq
    translation_key: menu.faq
    
footer_menu:
  - path: mailto:sdg_nsc@stat.kg
    translation_key: menu.contact_us
  - path: about/cookies-and-privacy
    translation_key: menu.cookies


# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

# The list of languages that are translated. The first one is the default.
languages:
  - ru
  - en
  - ky
  
metadata_tabs:
  - scope: indicator_information
    title: custom.indicator_information
    blurb: custom.indicator_information_blurb
  - scope: national
    title: indicator.national_metadata
    blurb: indicator.national_metadata_blurb
  - scope: data_reporter
    title: custom.data_reporter
    blurb: custom.data_reporter_blurb


# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "ru"

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: https://sdg-kyrgyzstan.github.io/open-sdg-site-starter/assets/img/goals


# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-get-json
  - jekyll-open-sdg-plugins

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@2.3.2

# Apply any custom Javascript.
custom_js:
  - /assets/js/custom.js

# Apply any custom CSS.
custom_css:
  - /assets/css/custom.css
  
# Mapping
map_options:
  disaggregation_controls: false
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
map_layers:
  - min_zoom: 5
    max_zoom: 10
    subfolder: oblasts
    label: indicator.map
    staticBorders: false

frontpage_goals_grid:
  title: frontpage.heading
  description: frontpage.instructions
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body

logos:
  - language: ru
    src: assets/img/SDG_logo_ru.png
    alt: Цели в области устойчивого развития - 17 Целей, чтобы преобразовать наш мир
  - language: en
    src: assets/img/SDG_logo_en.png
    alt: Sustainable Development Goals - 17 Goals to Transform our World

observation_attributes: 
  - field: COMMENT_OBS 
    label: '' 
    
reporting_status:
    disaggregation_indicator_count_label: indicators in scope

    use_new_config_forms: true 
    
disclaimer:
  hidden: true
