name: Temp Deploy Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy test
        uses: jamesives/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
          CLEAN: true
